# Change these first
owner: glytchClaw # Your GitHub organization or username, where this repository lives
repo: backupptime # The name of this repository

sites:
  - name: Primary gotify server
    url: https://gotipi.glynch.dev

status-website:
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /backupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Backupptime instance
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
